In [6]:
import numpy as np
Z = np.diag(np.arange(1, 5), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [84]:
arr = np.random.random((10, 3))
print(arr)
    
(0.5 + np.min(np.fabs(arr-0.5), axis = 1))[np.min(arr -0.5, axis = 1) != np.min(np.fabs(arr-0.5), axis = 1)]

# (0.5 + np.min(np.fabs(arr-0.5), axis = 1))

# 0.5 + np.min(arr -0.5, axis = 1) != 0.5 + np.min(np.fabs(arr-0.5), axis = 1)

[[0.76394856 0.71074192 0.57073384]
 [0.13109218 0.35912212 0.48494093]
 [0.16295389 0.17192444 0.91495485]
 [0.82214742 0.98510211 0.537318  ]
 [0.19343417 0.04208858 0.38772326]
 [0.70163522 0.36226156 0.53019866]
 [0.15991942 0.2242868  0.0195853 ]
 [0.60355881 0.70241527 0.11123747]
 [0.73564568 0.18038333 0.57695721]
 [0.13267901 0.75642215 0.03206936]]


array([0.51505907, 0.82807556, 0.61227674, 0.53019866, 0.7757132 ,
       0.60355881, 0.57695721, 0.75642215])

In [51]:
arr = np.random.random((6, 6))
np.sum(arr, axis = 1)/np.max(arr, axis = 1)

array([4.02723142, 3.12495295, 3.37881592, 3.09991846, 3.04966049,
       3.94204596])

In [62]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x[np.unique(i, return_counts = True)[0]] = x[np.unique(i, return_counts = True)[0]] + np.unique(i, return_counts = True)[1] 
x


array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

In [69]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.max(x[(np.argwhere(x == 0)+1)%x.shape])

6

In [74]:
x = 1.235
round(x), int(x), np.floor(x)

(1, 1, 1.0)

In [ ]:
def kNN(train_X, train_Y ,test_X, k=8):
    for i in test_X:
        